cart/urls.py
from django.urls import path
from .views import (
    cart_detail,
    # add_to_cart,
    delete_product,
    update_product,
)

app_name = "cart"

urlpatterns = [
    path("", cart_detail, name="cart_detail"),
    path("delete/<int:id>", delete_product, name="delete_product"),
    path("update/<int:id>", update_product, name="update_product"),
]

online_store/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from profile.views import Profile
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls")),
    path("", include("profile.urls")),
    path("products/", include("products.urls")),
    path("orders/", include("orders.urls")),
    # path('password/', auth_views.PasswordChangeView.as_view(), name='password'),
    # path('password-reset/', auth_views.PasswordResetView.as_view(
    #     template_name='profile/password_reset_form.html'),
    #      name='password_reset'),
    # path('password-reset/done/',
    #      auth_views.PasswordResetCompleteView.as_view(template_name='profile/password_reset_done.html'),
    #      name='password_reset_done'),
    # path('reset/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(template_name='profile/password_reset_confirm.html'),
    #      name='password_reset_confirm'),
    # path('reset/done/',
    #      auth_views.PasswordResetCompleteView.as_view(template_name='profile/password_reset_complete.html'),
    #      name='password_reset_complete'),
    # path('password-change/',
    #      auth_views.PasswordChangeView.as_view(template_name='profile/password_change_form.html'),
    #      name='password_change'),
    # path('password-change/done/',
    #      auth_views.PasswordChangeDoneView.as_view(template_name='profile/password_change_done.html'),
    #      name='password_change_done'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders.views import (
    OrderView,
    PaymentView,
    PaymentProgressView,
    payment_success,
    payment_not_success,
    PaymentControlView,
    order_step_1,
    order_step_2,
    order_step_3,
    OrderStepFour,
    OrderHistory,
    order_detail,
)

app_name = "orders"

urlpatterns = [
    path("order/", OrderView.as_view(), name="order"),
    path("payment/", PaymentView.as_view(), name="payment"),
    path("payment_progress/", PaymentProgressView.as_view(), name="payment_progress"),
    path("control/<int:num>", PaymentControlView.as_view(), name="control"),
    path("success/", payment_success, name="success"),
    path("not_success/", payment_not_success, name="not_success"),
    path("order_step_1/", order_step_1, name="order_step_1"),
    path("order_step_2/", order_step_2, name="order_step_2"),
    path("order_step_3/", order_step_3, name="order_step_3"),
    path("order_step_4/", OrderStepFour.as_view(), name="order_step_4"),
    path("order_history/", OrderHistory.as_view(), name="order_history"),
    path("order_detail/<int:pk>", order_detail, name="order_detail"),
]

products/urls.py
from django.urls import path

from products.views import (
    CatalogView,
    CategoryView,
    TagView,
    product_detail,
    product_reviews,
    catalog_product,
    all_catalog,
)
from django.conf import settings
from django.conf.urls.static import static

app_name = "products"

urlpatterns = [
    path("catalog/<int:sort>", all_catalog, name="catalog"),
    path("product/<int:pk>/", product_detail, name="product"),
    path("category/<int:pk>/", CategoryView.as_view(), name="category"),
    path("tag/<int:pk>/", TagView.as_view(), name="tag"),
    path("product_reviews/<int:pk>/", product_reviews, name="product_reviews"),
    path("catalog_query/", catalog_product, name="catalog_query"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product
from profile.models import Profile


class Cart(models.Model):  # корзина пользователя
    username = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name="profile"
    )
    product = models.ForeignKey(
        Product, default=1, on_delete=models.CASCADE, related_name="product"
    )
    quantity = models.PositiveIntegerField(default=0)
    create_at = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = "Корзина"
        verbose_name_plural = "Корзины"


class Payment(models.Model):
    number = models.IntegerField(default=0, verbose_name="номер счета")
    name = models.TextField(max_length=30, default="не указан")
    month = models.DateField(auto_now_add=True)
    year = models.DateField(auto_now_add=True)
    code = models.IntegerField(default=0, verbose_name="код оплаты")

    class Meta:
        verbose_name = "Оплата"
        verbose_name_plural = "Оплата"

    def __str__(self):
        return self.name

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    """Form for adding product to cart"""

    amount = forms.IntegerField(min_value=1)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.http import HttpRequest
from django.shortcuts import render, redirect
from products.models import Product
from cart.models import Cart
from django.db import transaction


def cart_detail(request: HttpRequest, **kwargs):
    return redirect("cart")


def delete_product(request: HttpRequest, **kwargs):
    with transaction.atomic():
        product = Cart.objects.get(id=kwargs["id"])
        Cart.objects.get(id=kwargs["id"]).delete()

        prod_count = Product.objects.get(id=product.product.id)
        count = product.quantity + prod_count.count
        Product.objects.filter(id=product.product.id).update(count=count)
    return redirect(request.META["HTTP_REFERER"])


def update_product(request: HttpRequest, **kwargs):
    product = Cart.objects.get(id=kwargs["id"])
    old_count = product.quantity
    count = request.POST.get("amount")
    prod_count = Product.objects.get(id=product.product.id)
    if old_count > int(count):
        remove = product.product.count
        new_count = prod_count.count + (old_count - int(count))
    else:
        remove = int(count) - old_count
        new_count = prod_count.count - (int(count) - old_count)
    if product.product.count >= remove:
        with transaction.atomic():
            Cart.objects.filter(id=kwargs["id"]).update(
                quantity=count,
            )

            Product.objects.filter(id=product.product.id).update(count=new_count)

    return redirect(request.META["HTTP_REFERER"])

cart/templates/cart/cart.html
{% extends "profile/base.html" %}
{% load static %}
{% load products_tags %}
{% block content %}
    {% cart_list pk=request.user.profile.pk as cart %}
    {% cart_total_price pk=request.user.profile.pk as total_price %}
    {% for product in cart %}
        <div class="Middle Middle_top">
            <div class="Section">
                <div class="wrap">
                    <form class="form" action="{% url 'cart:update_product' id=product.pk %}" method="post">
                    {% csrf_token %}
                        <div class="Cart-product">

                            <div class="Cart-block Cart-block_row">
                            <div class="Cart-block Cart-block_pict"><a class="Cart-pict" href="{% url 'products:product' pk=product.product.pk %}"><img class="Cart-img" src="{{ product.product.product_picture.url }} " alt="card.jpg" /></a>
                            </div>
                            <div class="Cart-block Cart-block_info"><a class="Cart-title" href="{% url 'products:product' pk=product.product.pk %}">{{ product.product.title }}</a>
                                <div class="Cart-desc">{{ product.product.description }}
                                </div>
                            </div>
                            <div class="Cart-block Cart-block_price">
                                <div class="Cart-price">{{ product.product.price }}
                                </div>
                            </div>
                        </div>

                        <div class="Cart-block Cart-block_row">
                            <div class="Cart-block Cart-block_seller">
                                <!-- - var options = setOptions(items, ['value', 'selected', 'disabled']);-->

                            </div>
                            <div class="Cart-block Cart-block_amount">
                                <div class="Cart-amount">
                                    <div class="Amount">
                                        <button class="Amount-remove" type="submit">
                                        </button>
                                        <input class="Amount-input" name="amount" min="1" type="text" value="{{ product.quantity }}" />
                                        <button class="Amount-add" type="submit">
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <div class="Cart-block Cart-block_delete"><button type="submit" class="btn btn_primary btn_lg">Обновить</button></div>
                           <div class="Cart-block Cart-block_delete"><a class="Cart-delete" href="{% url 'cart:delete_product' id=product.pk %}"><img src="{% static 'assets/img/icons/card/delete.svg' %}" alt="delete.svg" /></a>
                           </div>
                        </div>
                        </div>
                    </form>
    {% endfor %}
                        {% if cart %}
                            <div class="Cart-total">
                                <div class="Cart-block Cart-block_total">
                                    <strong class="Cart-title">Итого:
                                    </strong><span class="Cart-price">{{ total_price }}</span>
                                </div>

                            <div class="Cart-block"><a class="btn btn_success btn_lg" href="{% url 'orders:order_step_1' %}">Оформить заказ</a>
                            </div>
                        {% else %}
                            <div class="Cart-total">
                                <div class="Cart-block Cart-block_total">
                                    <strong class="Cart-title">Корзина пуста</strong>
                                </div>
                            </div>
                        {% endif %}
                    </div>
            </div>
        </div>
    </div>
{% endblock %}

cart/templates/cart/detail.html
{% extends "profile/base.html" %}
{% load static %}
{% load products_tags %}
{% block title %}
    Корзина
{% endblock %}
{% block content %}
    <h1>Корзина покупок</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Изображение товара</th>
            <th>Название</th>
            <th>Обновить количество</th>
            <th>Удалить</th>
            <th>Цена за 1 ед.</th>
            <th>Цена</th>
        </tr>
        </thead>
        {% cart_products pk=request.user.profile.pk as cart %}
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.product_picture %}{{ product.product_picture.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>
                        <form action="{% url 'cart:cart_add' product_id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" value="Обновить">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td><a href="{% url "cart:cart_remove" product.id%}">Remove</a></td>
                    <td>{{ item.quantity }}</td>
                    <td class="num">{{ item.price }}</td>
                    <td class="num">{{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Общая стоимость</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "products:catalog" %}" class="button light">Продолжить покупки</a>
        <a href="#" class="button">Оформить заказ</a>
    </p>
{% endblock %}