cart/urls.py
from django.urls import path
from .views import (
    cart_detail,
    # add_to_cart,
    delete_product,
    update_product,
)

app_name = "cart"

urlpatterns = [
    path("", cart_detail, name="cart_detail"),
    path("delete/<int:id>", delete_product, name="delete_product"),
    path("update/<int:id>", update_product, name="update_product"),
]

my_store_app/urls.py
from django.contrib import admin
from django.urls import include, path
from my_store_app.views import (CategoryView,
                                register_view,
                                AuthorLogoutView,
                                Login,
                                AccountView,
                                ProfileView,
                                CartView,
                                avatar,)
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views

app_name = 'my_store_app'

urlpatterns = [
    path('', CategoryView.as_view(), name='index'),
    path('register/', register_view, name='register'),
    path('logout/', AuthorLogoutView.as_view(), name='logout'),
    path('login/', Login.as_view(template_name='my_store_app/login.html'), name='login'),
    path('email/', views.PasswordResetView.as_view(), name='email'),
    path('account/', AccountView.as_view(), name='account'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('cart/<int:pk>', CartView.as_view(), name='cart'),
    path('avatar/<int:id>', avatar, name='avatar'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

online_store/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from profile.views import Profile
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls")),
    path("", include("profile.urls")),
    path("products/", include("products.urls")),
    path("orders/", include("orders.urls")),
    # path('password/', auth_views.PasswordChangeView.as_view(), name='password'),
    # path('password-reset/', auth_views.PasswordResetView.as_view(
    #     template_name='profile/password_reset_form.html'),
    #      name='password_reset'),
    # path('password-reset/done/',
    #      auth_views.PasswordResetCompleteView.as_view(template_name='profile/password_reset_done.html'),
    #      name='password_reset_done'),
    # path('reset/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(template_name='profile/password_reset_confirm.html'),
    #      name='password_reset_confirm'),
    # path('reset/done/',
    #      auth_views.PasswordResetCompleteView.as_view(template_name='profile/password_reset_complete.html'),
    #      name='password_reset_complete'),
    # path('password-change/',
    #      auth_views.PasswordChangeView.as_view(template_name='profile/password_change_form.html'),
    #      name='password_change'),
    # path('password-change/done/',
    #      auth_views.PasswordChangeDoneView.as_view(template_name='profile/password_change_done.html'),
    #      name='password_change_done'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders.views import (
    OrderView,
    PaymentView,
    PaymentProgressView,
    payment_success,
    payment_not_success,
    PaymentControlView,
    order_step_1,
    order_step_2,
    order_step_3,
    OrderStepFour,
    OrderHistory,
    order_detail,
)

app_name = "orders"

urlpatterns = [
    path("order/", OrderView.as_view(), name="order"),
    path("payment/", PaymentView.as_view(), name="payment"),
    path("payment_progress/", PaymentProgressView.as_view(), name="payment_progress"),
    path("control/<int:num>", PaymentControlView.as_view(), name="control"),
    path("success/", payment_success, name="success"),
    path("not_success/", payment_not_success, name="not_success"),
    path("order_step_1/", order_step_1, name="order_step_1"),
    path("order_step_2/", order_step_2, name="order_step_2"),
    path("order_step_3/", order_step_3, name="order_step_3"),
    path("order_step_4/", OrderStepFour.as_view(), name="order_step_4"),
    path("order_history/", OrderHistory.as_view(), name="order_history"),
    path("order_detail/<int:pk>", order_detail, name="order_detail"),
]

products/urls.py
from django.urls import path

from products.views import (
    CatalogView,
    CategoryView,
    TagView,
    product_detail,
    product_reviews,
    catalog_product,
    all_catalog,
)
from django.conf import settings
from django.conf.urls.static import static

app_name = "products"

urlpatterns = [
    path("catalog/<int:sort>", all_catalog, name="catalog"),
    path("product/<int:pk>/", product_detail, name="product"),
    path("category/<int:pk>/", CategoryView.as_view(), name="category"),
    path("tag/<int:pk>/", TagView.as_view(), name="tag"),
    path("product_reviews/<int:pk>/", product_reviews, name="product_reviews"),
    path("catalog_query/", catalog_product, name="catalog_query"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

profile/urls.py
from django.contrib import admin
from django.urls import include, path
from profile.views import (
    CategoryView,
    register_view,
    AuthorLogoutView,
    Login,
    AccountView,
    ProfileView,
    CartView,
    avatar,
)
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.contrib.auth import views as auth_views

# app_name = 'profile'

urlpatterns = [
    path("", CategoryView.as_view(), name="index"),
    path("register/", register_view, name="register"),
    path("logout/", AuthorLogoutView.as_view(), name="logout"),
    path("login/", Login.as_view(template_name="profile/login.html"), name="login"),
    path("email/", views.PasswordResetView.as_view(), name="email"),
    path("account/", AccountView.as_view(), name="account"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("cart/<int:pk>", CartView.as_view(), name="cart"),
    path("avatar/<int:id>", avatar, name="avatar"),
    path("password/", auth_views.PasswordChangeView.as_view(), name="password"),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="profile/password_reset_form.html"
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="profile/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="profile/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="profile/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "password-change/",
        auth_views.PasswordChangeView.as_view(
            template_name="profile/password_change_form.html"
        ),
        name="password_change",
    ),
    path(
        "password-change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="profile/password_change_done.html"
        ),
        name="password_change_done",
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    """Form for adding product to cart"""

    amount = forms.IntegerField(min_value=1)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.http import HttpRequest
from django.shortcuts import render, redirect
from products.models import Product
from cart.models import Cart
from django.db import transaction


def cart_detail(request: HttpRequest, **kwargs):
    return redirect("cart")


def delete_product(request: HttpRequest, **kwargs):
    with transaction.atomic():
        product = Cart.objects.get(id=kwargs["id"])
        Cart.objects.get(id=kwargs["id"]).delete()

        prod_count = Product.objects.get(id=product.product.id)
        count = product.quantity + prod_count.count
        Product.objects.filter(id=product.product.id).update(count=count)
    return redirect(request.META["HTTP_REFERER"])


def update_product(request: HttpRequest, **kwargs):
    product = Cart.objects.get(id=kwargs["id"])
    old_count = product.quantity
    count = request.POST.get("amount")
    prod_count = Product.objects.get(id=product.product.id)
    if old_count > int(count):
        remove = product.product.count
        new_count = prod_count.count + (old_count - int(count))
    else:
        remove = int(count) - old_count
        new_count = prod_count.count - (int(count) - old_count)
    if product.product.count >= remove:
        with transaction.atomic():
            Cart.objects.filter(id=kwargs["id"]).update(
                quantity=count,
            )

            Product.objects.filter(id=product.product.id).update(count=new_count)

    return redirect(request.META["HTTP_REFERER"])

my_store_app/views.py
from django.contrib import messages
from django.http import HttpRequest
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView

from my_store_app.models import Profile
from products.models import Product, TagsFile, Reviews, Specifications, Shop, Sales, CategoryProduct
from orders.models import Order, OrderHistory
from cart.models import Cart, Payment

from my_store_app.forms import AuthorRegisterForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LogoutView, LoginView
from django.contrib.auth.models import User
import os
from django.core.exceptions import ValidationError
from cart.forms import CartAddProductForm


def register_view(request):
    """Функция регистрации нового пользователя"""

    if request.method == 'POST':
        form = AuthorRegisterForm(request.POST)
        if form.is_valid():
            full_name = form.cleaned_data.get('full_name')
            phone = form.cleaned_data.get('phone')
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password')
            username = form.cleaned_data.get('login')
            user = User.objects.create_user(username=username, first_name=full_name, email=email)
            user.set_password(raw_password)
            user.save()
            login(request, user)
            Profile.objects.create(user=user, username=username, full_name=full_name, phone=phone, email=email)
        return redirect('/')

    return render(request, 'my_store_app/registr.html')


class AuthorLogoutView(LogoutView):
    """Выход из учетной записи"""

    next_page = '/'


class Login(LoginView):
    """Вход в учетную запись"""

    def form_valid(self, form):
        return super().form_valid(form)


class CategoryView(View):
    """Формирование списка категорий, популярных товаров,
     лимитированных, баннеров и путей до изображений этих категорий"""

    def get(self, request):
        date = CategoryProduct.objects.all()
        file_name_list = []
        for image in date:
            file = os.path.basename(str(image.image))
            file_name_list.append(file)
        category = zip(date, file_name_list)
        popular_product = Product.objects.all().order_by('-reviews')[:8]
        limited_edition = Product.objects.filter(free_delivery=False)
        banners = Product.objects.all().order_by('-rating')
        return render(request, 'my_store_app/index.html', {'popular_product': popular_product,
                                                           'limited_edition': limited_edition,
                                                           'banners': banners})


class AccountView(View):
    def get(self, request: HttpRequest):
        return render(request, 'my_store_app/account.html')


class ProfileView(View):
    def get(self, request: HttpRequest):
        return render(request, 'my_store_app/profile.html')


class CartView(View):
    def get(self, request: HttpRequest, **kwargs):
        cart = Cart.objects.filter(username=kwargs['pk'])
        total_price = 0
        for product in cart:
            total_price += product.product.price * product.quantity
        return render(request, 'cart/cart.html', {'total_price': total_price})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'products/product.html', {'product': product,
                                                     'cart_product_form': cart_product_form})


def avatar(request: HttpRequest, **kwargs):
    user = Profile.objects.get(user=kwargs['id'])
    user_avatar = request.POST.get('avatar')

    Profile.objects.filter(user=kwargs['id']).update(
        avatar=user_avatar,
    )
    return redirect(request.META['HTTP_REFERER'])

profile/views.py
from django.contrib import messages
from django.http import HttpRequest
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView

from profile.models import Profile
from products.models import (
    Product,
    TagsFile,
    Reviews,
    Specifications,
    Shop,
    Sales,
    CategoryProduct,
)
from orders.models import Order, OrderHistory
from cart.models import Cart, Payment

from profile.forms import AuthorRegisterForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LogoutView, LoginView
from django.contrib.auth.models import User
import os
from django.core.exceptions import ValidationError
from cart.forms import CartAddProductForm


def register_view(request):
    """Функция регистрации нового пользователя"""

    if request.method == "POST":
        form = AuthorRegisterForm(request.POST)
        if form.is_valid():
            full_name = form.cleaned_data.get("full_name")
            phone = form.cleaned_data.get("phone")
            email = form.cleaned_data.get("email")
            raw_password = form.cleaned_data.get("password")
            username = form.cleaned_data.get("login")
            user = User.objects.create_user(
                username=username, first_name=full_name, email=email
            )
            user.set_password(raw_password)
            user.save()
            login(request, user)
            Profile.objects.create(
                user=user,
                username=username,
                full_name=full_name,
                phone=phone,
                email=email,
            )
        return redirect("/")

    return render(request, "profile/registr.html")


class AuthorLogoutView(LogoutView):
    """Выход из учетной записи"""

    next_page = "/"


class Login(LoginView):
    """Вход в учетную запись"""

    def form_valid(self, form):
        return super().form_valid(form)


class CategoryView(View):
    """Формирование списка категорий, популярных товаров,
    лимитированных, баннеров и путей до изображений этих категорий"""

    def get(self, request):
        date = CategoryProduct.objects.all()
        file_name_list = []
        for image in date:
            file = os.path.basename(str(image.image))
            file_name_list.append(file)
        category = zip(date, file_name_list)
        popular_product = Product.objects.all().order_by("-reviews")[:8]
        limited_edition = Product.objects.filter(free_delivery=False)
        banners = Product.objects.all().order_by("-rating")
        return render(
            request,
            "profile/index.html",
            {
                "popular_product": popular_product,
                "limited_edition": limited_edition,
                "banners": banners,
            },
        )


class AccountView(View):
    def get(self, request: HttpRequest):
        return render(request, "profile/account.html")


class ProfileView(View):
    def get(self, request: HttpRequest):
        return render(request, "profile/profile.html")


class CartView(View):
    def get(self, request: HttpRequest, **kwargs):
        cart = Cart.objects.filter(username=kwargs["pk"])
        total_price = 0
        for product in cart:
            total_price += product.product.price * product.quantity
        return render(request, "cart/cart.html", {"total_price": total_price})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(
        request,
        "products/product.html",
        {"product": product, "cart_product_form": cart_product_form},
    )


def avatar(request: HttpRequest, **kwargs):
    user = Profile.objects.get(user=kwargs["id"])
    user_avatar = request.POST.get("avatar")

    Profile.objects.filter(user=kwargs["id"]).update(
        avatar=user_avatar,
    )
    return redirect(request.META["HTTP_REFERER"])

my_store_app/templates/my_store_app/base.html
<!--END-->
<!--END-->
<!DOCTYPE html>
{% load static %}
{% load products_tags %}
{% include 'include/head.html' %}
<!--[if IE 7]>
<html class="ie7" lang="ru">
<![endif]-->
<!--[if IE 8]>
<html class="ie8" lang="ru">
<![endif]-->
<!--[if IE 9]>
<html class="ie9" lang="ru">
<![endif]-->
<!--[if IE 10]>
<html class="ie10" lang="ru">
<![endif]-->
<!--[if IE 11]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!-->
<html lang="ru">
<!--<![endif]-->

<body class="Site">
    <!--if lt IE 8
  p.error-browser
      | Ваш браузер&nbsp;
      em устарел!&nbsp;
      a(href="http://browsehappy.com/") Выберите новую версию
          +s
          | браузера здесь&nbsp;
      | для правильного отображения сайта.
  -->
    <header class="Header">
        <div class="ControlPanel">
            <div class="wrap">
                <div class="row ControlPanel-row">
                    <div class="row-block">
                        <div class="row ControlPanel-rowSplit">
                            <div class="row-block hide_700">
                                <ul class="menu menu_img menu_smallImg ControlPanel-menu">
                                    <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialHeader/fb.svg' %}" alt="fb.svg" /></a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialHeader/tw.svg' %}" alt="tw.svg" /></a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialHeader/in.svg' %}" alt="in.svg" /></a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialHeader/pt.svg' %}" alt="pt.svg" /></a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialHeader/mail.svg' %}" alt="mail.svg" /></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <nav class="row-block">
                        <div class="row ControlPanel-rowSplit">
                            {% if request.user.is_authenticated %}
                                {{ request.user.first_name }}
                                <div class="row-block"><a class="ControlPanel-title" href="{% url 'my_store_app:logout' %}">Выход</a></div>
                            {% else %}
                            <div class="row-block"><a class="ControlPanel-title" href="{% url 'my_store_app:login' %}">Вход</a>
                                <a class="ControlPanel-title" href="{% url 'my_store_app:register' %}">Регистрация</a></div>
                            {% endif %}
                        </div>
                    </nav>
                </div>
            </div>
            <!--+div.menuModal#navigate
      //    +menu([
      //        ['Главная','index.html'],
      //        ['Портфолио','index.html'],
      //        ['Мои проекты','index.html'],
      //        ['Контакты','index.html']
      //    ], page === 'article'? 'Портфолио': 'Главная')._main

      block
      -->
        </div>
        <div class="wrap">
            <div class="row Header-rowMain">
                <div class="row-block Header-logo"><a class="logo" href="{% url 'my_store_app:index' %}"><img class="logo-image" src="{% static 'assets/img/logo.png' %}" alt="logo.png" /></a>
                </div>
                <nav class="row-block row-block_right Header-menu">
                    <div class="menuModal" id="navigate">
                        <ul class="menu menu_main">
                            <li class="menu-item"><a class="menu-link" href="{% url 'my_store_app:index' %}">Главная</a>
                            </li>
                            <li class="menu-item"><span class="menu-label menu-label_success">Скидки</span><a class="menu-link" href="{% url 'products:catalog' sort=9 %}">Каталог</a>
                            </li>
                            <li class="menu-item"><a class="menu-link" href="comparison.html">Сравнение</a>
                            </li>
                        </ul>
                    </div>
                </nav>
                <div class="row-block">

                    <div class="CartBlock">
                        {% with total_items=cart|length %}
                            <div class="dropdown">
                                <button class="dropbtn"><img class="CartBlock-img" src="{% static 'assets/img/icons/loon-icon.svg' %}" alt="loon-icon.svg" /></button>
                                <div class="dropdown-content">
                                    <a class="dropdown-content-a" href="{% url 'my_store_app:account' %}">Личный кабинет</a>
                                    <a class="dropdown-content-a" href="account.html">Административный раздел</a>
                                    <a class="dropdown-content-a" href="{% url 'my_store_app:logout' %}">Выход</a>
                                </div>
                            </div>
                            {% cart_products pk=request.user.profile.pk as count %}
                            {% cart_total_price pk=request.user.profile.pk as total_price %}
                            {% cart_view pk=request.user.profile.pk as way%}
                            <a class="CartBlock-block" href="{% url 'my_store_app:cart' pk=way %}"><img class="CartBlock-img" src="{% static 'assets/img/icons/cart.svg' %}" alt="cart.svg" /><span class="CartBlock-amount">{{ count }}</span></a>
                            <div class="CartBlock-block"><span class="CartBlock-price">{{ total_price }}</span>
                        {% endwith %}


                        </div>
                    </div>
                </div>
                <div class="row-block Header-trigger"><a class="menuTrigger" href="#navigate">
                        <div class="menuTrigger-content">Показать навигацию
                        </div><span></span><span></span><span></span>
                    </a>
                </div>
            </div>
        </div>
        <div class="Header-searchWrap">
            <div class="wrap">
                <div class="Header-categories">
                    <div class="CategoriesButton">
                        <div class="CategoriesButton-title">
                            <div class="CategoriesButton-icon"><img src="{% static 'assets/img/icons/allDep.svg' %}" alt="allDep.svg" />
                            </div><span class="CategoriesButton-text">Все категории</span>
                            <div class="CategoriesButton-arrow">
                            </div>
                        </div>
                        <div class="CategoriesButton-content">
                        {% all_category as categories %}
                            {% for cat in categories %}
                                <div class="CategoriesButton-link"><a href="{% url 'products:category' pk=cat.pk %}">
                                    <div class="CategoriesButton-icon"><img src="{{cat.image.url}}" alt="{{image}}" />
                                    </div><span class="CategoriesButton-text">{{cat.title}}</span>
                                </a>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="Header-searchLink"><img src="{% static 'assets/img/icons/search.svg' %}" alt="search.svg" />
                </div>
                <div class="Header-search">
                    <div class="search">
                        <form class="form form_search" action="{% url 'products:catalog_query' %}" method="post">
                            {% csrf_token %}
                            <input class="search-input" id="title" name="title" type="text" placeholder="Введите название товара для поиска" />
                            <button class="search-button" type="submit" name="search" id="search"><img src="{% static 'assets/img/icons/search.svg' %}" alt="search.svg" />Поиск
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </header>

{% block content %} {% endblock content %}


    <footer class="Footer">
        <div class="wrap">
            <div class="row Footer-main">
                <div class="row-block"><a class="logo Footer-logo" href="{% url 'my_store_app:index' %}"><img class="logo-image" src="{% static 'assets/img/logo_footer.png' %}" alt="logo_footer.png" /></a>
                </div>
                <div class="row-block">
                    <strong class="Footer-title">Навигация
                    </strong>
                    <ul class="menu menu_vt Footer-menu">
                        <li class="menu-item"><a class="menu-link" href="{% url 'my_store_app:index' %}">Главная</a>
                        </li>
                        <li class="menu-item"><a class="menu-link" href="../../../products/templates/products/catalog.html">Каталог</a>
                        </li>
                        <li class="menu-item"><a class="menu-link" href="comparison.html">Сравнение</a>
                        </li>
                        <li class="menu-item"><a class="menu-link" href="account.html">Профиль</a>
                        </li>

                    </ul>
                </div>
                <div class="row-block">
                    <strong class="Footer-title">Контакты
                    </strong>
                    <p>Phone: 8.800.200.600<br>Email: xxx@meg.com<br>
                    </p>
                    <ul class="menu menu_img menu_smallImg Footer-menuSoc">
                        <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialFooter/fb.svg' %}" alt="fb.svg" /></a>
                        </li>
                        <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialFooter/tw.svg' %}" alt="tw.svg" /></a>
                        </li>
                        <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialFooter/in.svg' %}" alt="in.svg" /></a>
                        </li>
                        <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialFooter/pt.svg' %}" alt="pt.svg" /></a>
                        </li>
                        <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialFooter/mail.svg' %}" alt="mail.svg" /></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!--+Middle-->
    <!--    +div.-top-->
    <!--        +breadcrumbs('Главная','Портфолио')-->
    <!--    +Article('portfolio')-->
    <!---->
    <script src="{% static 'assets/plg/jQuery/jquery-3.5.0.slim.min.js' %}"></script>
    <script src="{% static 'assets/plg/form/jquery.form.js' %}"></script>
    <script src="{% static 'assets/plg/form/jquery.maskedinput.min.js' %}"></script>
    <script src="{% static 'assets/plg/range/ion.rangeSlider.min.js' %}"></script>
    <script src="{% static 'assets/plg/Slider/slick.min.js' %}"></script>
    <script src="{% static 'assets/js/scripts.js' %}"></script>
</body>

</html>

my_store_app/templates/my_store_app/e-mail.html
{% extends 'my_store_app/base_register.html' %}
{% load static %}
{% block content %}
            <div class="wrapper">
                <div class="header">
                    <h3 class="sign-in">Восстановление пароля (1/2)</h3>
                    <h5>Для восстановления пароля введите адрес электронной почты, на которую зарегистрирована учетная запись</h5>
                </div>

                <form action="{% url 'my_store_app:password' %}">

                    <div>
                        <input class="user-input" type="email" name="email" id="name" placeholder="E-mail" />
                    </div>
                    <div>
                        <input type="submit" value="Получить проверочный код" />
                    </div>
                    <a class="registr" href="{% url 'my_store_app:login' %}">
                        Вход
                    </a>
                </form>
            </div>
{% endblock %}

my_store_app/templates/my_store_app/login.html
{% extends 'my_store_app/base_register.html' %}
{% load static %}
{% block content %}
            <div class="wrapper">
                <div class="header">
                    <h3 class="sign-in">Вход</h3>
                </div>
                <div class="clear"></div>


                <form action="/login/" method="post">
                    {% csrf_token %}
                    <div>
                        <input class="user-input" type="text" name="username" id="name" placeholder="Логин" />
                    </div>
                    <div>

                        <input type="password" name="password" id="name" placeholder="*********" />
                    </div>
                    <div>
                        <input type="submit" value="Войти" />
                    </div>
                    <a class="forgot-label" href="{% url 'password_reset' %}">Забыли пароль?</a>
                    <a class="registr" href="{% url 'my_store_app:register' %}">Регистрация</a>
                </form>
            </div>

{% endblock %}