cart/urls.py
from django.urls import path
from .views import (
    cart_detail,
    # add_to_cart,
    delete_product,
    update_product,
)

app_name = "cart"

urlpatterns = [
    path("", cart_detail, name="cart_detail"),
    path("delete/<int:id>", delete_product, name="delete_product"),
    path("update/<int:id>", update_product, name="update_product"),
]

online_store/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from profile.views import Profile
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls")),
    path("", include("profile.urls")),
    path("products/", include("products.urls")),
    path("orders/", include("orders.urls")),
    # path('password/', auth_views.PasswordChangeView.as_view(), name='password'),
    # path('password-reset/', auth_views.PasswordResetView.as_view(
    #     template_name='profile/password_reset_form.html'),
    #      name='password_reset'),
    # path('password-reset/done/',
    #      auth_views.PasswordResetCompleteView.as_view(template_name='profile/password_reset_done.html'),
    #      name='password_reset_done'),
    # path('reset/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(template_name='profile/password_reset_confirm.html'),
    #      name='password_reset_confirm'),
    # path('reset/done/',
    #      auth_views.PasswordResetCompleteView.as_view(template_name='profile/password_reset_complete.html'),
    #      name='password_reset_complete'),
    # path('password-change/',
    #      auth_views.PasswordChangeView.as_view(template_name='profile/password_change_form.html'),
    #      name='password_change'),
    # path('password-change/done/',
    #      auth_views.PasswordChangeDoneView.as_view(template_name='profile/password_change_done.html'),
    #      name='password_change_done'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders.views import (
    OrderView,
    PaymentView,
    PaymentProgressView,
    payment_success,
    payment_not_success,
    PaymentControlView,
    order_step_1,
    order_step_2,
    order_step_3,
    OrderStepFour,
    OrderHistory,
    order_detail,
)

app_name = "orders"

urlpatterns = [
    path("order/", OrderView.as_view(), name="order"),
    path("payment/", PaymentView.as_view(), name="payment"),
    path("payment_progress/", PaymentProgressView.as_view(), name="payment_progress"),
    path("control/<int:num>", PaymentControlView.as_view(), name="control"),
    path("success/", payment_success, name="success"),
    path("not_success/", payment_not_success, name="not_success"),
    path("order_step_1/", order_step_1, name="order_step_1"),
    path("order_step_2/", order_step_2, name="order_step_2"),
    path("order_step_3/", order_step_3, name="order_step_3"),
    path("order_step_4/", OrderStepFour.as_view(), name="order_step_4"),
    path("order_history/", OrderHistory.as_view(), name="order_history"),
    path("order_detail/<int:pk>", order_detail, name="order_detail"),
]

products/urls.py
from django.urls import path

from products.views import (
    CatalogView,
    CategoryView,
    TagView,
    product_detail,
    product_reviews,
    catalog_product,
    all_catalog,
)
from django.conf import settings
from django.conf.urls.static import static

app_name = "products"

urlpatterns = [
    path("catalog/<int:sort>", all_catalog, name="catalog"),
    path("product/<int:pk>/", product_detail, name="product"),
    path("category/<int:pk>/", CategoryView.as_view(), name="category"),
    path("tag/<int:pk>/", TagView.as_view(), name="tag"),
    path("product_reviews/<int:pk>/", product_reviews, name="product_reviews"),
    path("catalog_query/", catalog_product, name="catalog_query"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from profile.models import Profile
from products.models import Product


class OrderHistory(models.Model):  # история покупок пользователя
    user_order = models.ForeignKey(
        Profile, on_delete=models.CASCADE, verbose_name="пользователь", null=True
    )
    product_order = models.ForeignKey(
        "products.Product", on_delete=models.CASCADE, verbose_name="товар"
    )
    payment_date = models.DateField(auto_now_add=True)
    delivery_type = models.TextField(
        max_length=30, default="не указан", verbose_name="способ доставки"
    )
    payment_type = models.TextField(
        max_length=30, default="не указан", verbose_name="способ оплаты"
    )
    total_cost = models.IntegerField(default=0, verbose_name="общая стоимость заказа")
    status = models.TextField(
        max_length=30, default="не указан", verbose_name="статус оплаты"
    )
    city = models.TextField(
        max_length=30, default="не указан", verbose_name="город доставки"
    )
    address = models.TextField(
        max_length=30, default="не указан", verbose_name="адрес доставки"
    )

    class Meta:
        verbose_name = "История покупок"
        verbose_name_plural = "Истории покупок"

    def __str__(self):
        return self.user_order.full_name


class Order(models.Model):  # покупка товаров из корзины
    DELIVERY_CHOICES = [("reg", "Обычная доставка"), ("exp", "Экспресс доставка")]

    PAYMENT_CHOICES = [
        ("card", "Онлайн картой"),
        ("cash", "Онлайн со случайного чужого счета"),
    ]

    customer = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        related_name="orders",
        verbose_name="customer",
    )
    fio = models.CharField(
        max_length=100, null=True, blank=True, verbose_name="name and lastname"
    )
    phone = models.CharField(
        max_length=16, null=True, blank=True, verbose_name="phone number"
    )
    email = models.EmailField(null=True, blank=True, verbose_name="email")
    delivery = models.CharField(
        max_length=3, choices=DELIVERY_CHOICES, default="reg", verbose_name="delivery"
    )
    payment_method = models.CharField(
        max_length=4,
        choices=PAYMENT_CHOICES,
        default="card",
        verbose_name="payment method",
    )
    city = models.CharField(max_length=25, null=True, blank=True, verbose_name="city")
    address = models.TextField(
        max_length=255, null=True, blank=True, verbose_name="address"
    )
    in_order = models.BooleanField(default=False, verbose_name="in order")
    paid = models.BooleanField(default=False, verbose_name="order is payed")
    braintree_id = models.CharField(
        max_length=150, blank=True, verbose_name="transaction id"
    )
    delivery_cost = models.DecimalField(
        max_digits=10, decimal_places=2, default=0, verbose_name="delivery cost"
    )
    product_order = models.ForeignKey(
        "products.Product",
        on_delete=models.CASCADE,
        null=True,
        verbose_name="товар",
        related_name="product_order",
    )
    count = models.IntegerField(
        default=0, verbose_name="колличество  товаров в корзине"
    )
    price = models.IntegerField(
        default=0, verbose_name="общая стоимость  товаров в корзине"
    )
    date = models.DateField(auto_now_add=True)
    free_delivery = models.BooleanField(
        default=False, verbose_name="наличие бесплатной доставки"
    )

    class Meta:
        verbose_name = "Покупка"
        verbose_name_plural = "Покупки"

    def __str__(self):
        return self.product_order


class ProductInOrder(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        unique=False,
        related_name="user",
    )
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        unique=False,
        related_name="order",
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        unique=False,
        related_name="prod",
    )
    quantity = models.PositiveIntegerField(default=0, null=True)

orders/forms.py
from django import forms

from orders.models import Order


class PaymentForm(forms.Form):
    numero1 = forms.CharField(max_length=10)


class OrderStepOneForm(forms.ModelForm):

    """
    Форма первого шага выполнения заказа.
    Добавление имени, фамилии, телефона и электронной почты
    к информации о заказе.
    """

    class Meta:
        model = Order
        fields = ["fio", "phone", "email"]


class OrderStepTwoForm(forms.ModelForm):

    """
    Форма второго шага выполнения заказа.
    Добавление типа доставки, города и адреса
    к информации о заказе.
    """

    class Meta:
        model = Order
        widgets = {
            "delivery": forms.RadioSelect(attrs={"class": "toggle-box"}),
            "address": forms.Textarea(attrs={"class": "form-textarea"}),
        }
        fields = ["delivery", "city", "address"]


class OrderStepThreeForm(forms.ModelForm):

    """
    Форма третьего шага выполнения заказа.
    Добавление способа оплаты
    к информации о заказе.
    """

    class Meta:
        model = Order
        widgets = {
            "payment_method": forms.RadioSelect(attrs={"class": "toggle-box"}),
        }
        fields = ["payment_method"]

orders/views.py
from django.http import HttpRequest
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import DetailView

from orders.models import Order, ProductInOrder
from products.models import Product
from cart.models import Cart
from .forms import PaymentForm, OrderStepOneForm, OrderStepTwoForm, OrderStepThreeForm


class OrderView(View):
    def get(self, request: HttpRequest):
        return render(request, "orders/order.html")


class PaymentView(View):
    def post(self, request: HttpRequest):
        form = PaymentForm(request.POST)
        order = Order.objects.filter(customer=request.user, in_order=True).last()
        if order.payment_method == "card":
            return render(request, "orders/payment.html", {"form": form})
        else:
            return render(request, "orders/paymentsomeone.html", {"form": form})


class PaymentProgressView(View):
    def get(self, request: HttpRequest):
        card = request.GET.get("numero1")
        number = []
        for i in card:
            if i != " ":
                number.append(i)
        num = number[-1]
        return render(request, "orders/progressPayment.html", {"num": num})


class PaymentControlView(View):
    def get(self, request: HttpRequest, num):
        if int(num) != 0 and int(num) % 2 == 0:
            order = Order.objects.filter(customer=request.user, in_order=True).last()
            cart = Cart.objects.filter(username=request.user.profile)

            for product in cart:
                ProductInOrder.objects.create(
                    user=request.user,
                    product=product.product,
                    order=order,
                    quantity=product.quantity,
                )
                product_rating = Product.objects.get(id=product.product.id)
                product_rating.rating += product.quantity
                product_rating.save()

            cart.delete()

            return redirect("orders:success")

        else:
            return redirect("orders:not_success")


def payment_success(request: HttpRequest):
    """
    Представление удачной оплаты

    ::Страница: Оплата заказа
    """
    return render(request, "orders/success.html")


def payment_not_success(request: HttpRequest):
    """
    Представление неудачной оплаты

    ::Страница: Оплата заказа
    """
    return render(request, "orders/not_success.html")


def order_step_1(request: HttpRequest):
    if request.method == "POST":
        form = OrderStepOneForm(request.POST)

        if form.is_valid():
            if request.user.is_authenticated:
                fio = form.cleaned_data["fio"]
                email = form.cleaned_data["email"]
                phone = form.cleaned_data["phone"]

                order = Order.objects.filter(customer=request.user, in_order=False)

                if not order.exists():
                    Order.objects.create(
                        fio=fio, email=email, phone=phone, customer=request.user
                    )

                else:
                    order = Order.objects.filter(
                        customer=request.user, in_order=False
                    ).last()
                    order.fio = fio
                    order.email = email
                    order.phone = phone
                    order.save()

                return redirect("orders:order_step_2")
            else:
                return redirect("login")
    else:
        form = OrderStepOneForm()
        return render(request, "orders/order_step_1.html", {"form": form})


def order_step_2(request: HttpRequest):
    if request.method == "POST":
        form = OrderStepTwoForm(request.POST)
        order = Order.objects.get(customer=request.user, in_order=False)
        if form.is_valid():
            delivery = form.cleaned_data["delivery"]
            city = form.cleaned_data["city"]
            address = form.cleaned_data["address"]

            order.delivery = delivery
            order.city = city
            order.address = address
            order.save()

            return redirect("orders:order_step_3")
    else:
        form = OrderStepTwoForm()
        return render(request, "orders/order_step_2.html", {"form": form})


def order_step_3(request: HttpRequest):
    if request.method == "POST":
        form = OrderStepThreeForm(request.POST)
        order = Order.objects.get(customer=request.user, in_order=False)
        cart = Cart.objects.filter(username=request.user.profile)
        for product in cart:
            order.price += product.quantity * product.product.price

        if order.delivery == "exp":
            order.price += 500
            order.delivery_cost = 500.00
        elif order.price < 2000:
            order.price += 200
            order.delivery_cost = 200.00

        if form.is_valid():
            payment_method = form.cleaned_data["payment_method"]

            order.payment_method = payment_method
            order.in_order = True
            order.save()

            return redirect("orders:order_step_4")
    else:
        form = OrderStepThreeForm()
        return render(request, "orders/order_step_3.html", {"form": form})


class OrderStepFour(View):

    """
    Представление четвертого шага оформления заказа

    ::Страница: Оформление заказа
    """

    def get(self, request: HttpRequest):
        user = request.user
        if user.is_authenticated:
            order = Order.objects.filter(customer=user, in_order=True).last()
            return render(request, "orders/order_step_4.html", {"order": order})

        else:
            return redirect("login")


class OrderHistory(View):
    def get(self, request: HttpRequest):
        order = Order.objects.filter(customer=request.user, in_order=True).order_by(
            "-date"
        )
        return render(request, "orders/historyorder.html", {"order": order})


def order_detail(request: HttpRequest, **kwargs):
    order = Order.objects.get(customer=request.user, id=kwargs["pk"])
    return render(request, "orders/oneorder.html", {"order": order})

orders/templates/orders/historyorder.html
{% extends "profile/base.html" %}
{% load static %}
{% block content %}
    <div class="Middle Middle_top">
        <div class="Section Section_column Section_columnLeft">
            <div class="wrap">
                <div class="Section-column">
                    <div class="Section-columnSection">
                        <header class="Section-header">
                            <strong class="Section-title">Навигация
                            </strong>
                        </header>
                        <div class="Section-columnContent">
                            <div class="NavigateProfile">
                                <ul class="menu menu_vt">
                                    <li class="menu-item"><a class="menu-link" href="{% url 'account' %}">Личный кабинет</a>
                                    </li>
                                    <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="{% url 'profile' %}">Профиль</a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="{% url 'orders:order_history' %}">История заказов</a>
                                    </li>

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="Section-content">
                    <div class="Orders">
                        {% for item in order %}
                            <div class="Order Order_anons">
                                <div class="Order-personal">
                                    <div class="row">
                                        <div class="row-block"><a class="Order-title" href="{% url 'orders:order_detail' pk=item.pk %}">Заказ&#32;<span class="Order-numberOrder">{{ item.id }}</span>&#32;от&#32;<span class="Order-dateOrder">{{ item.date }}</span></a>
                                        </div>
                                        <div class="row-block">
                                            <div class="Order-info Order-info_delivery">
                                                <div class="Order-infoType">Тип доставки:
                                                </div>
                                                <div class="Order-infoContent">{{ item.delivery }}
                                                </div>
                                            </div>
                                            <div class="Order-info Order-info_pay">
                                                <div class="Order-infoType">Оплата:
                                                </div>
                                                <div class="Order-infoContent">{{ item.payment_method }}
                                                </div>
                                            </div>
                                            <div class="Order-info">
                                                <div class="Order-infoType">Общая стоимость:
                                                </div>
                                                <div class="Order-infoContent"><span class="Order-price">{{ item.price }}</span>
                                                </div>
                                            </div>
                                            <div class="Order-info Order-info_status">
                                                <div class="Order-infoType">Статус:
                                                </div>
                                                <div class="Order-infoContent">Oплачен
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

orders/templates/orders/order_step_4.html
{% extends "profile/base.html" %}
{% load static %}
{% load products_tags %}
{% block content %}
    {% order_user pk=request.user.pk as user %}
    <div class="Middle Middle_top">
        <div class="Section Section_column Section_columnRight Section_columnWide Order">
            <div class="wrap">

                <div class="Section-column">
                    <div class="Section-columnSection">
                        <header class="Section-header">
                            <strong class="Section-title">Прогресс заполнения
                            </strong>
                        </header>
                        <div class="Section-columnContent">
                            <div class="NavigateProfile">
                                <ul class="menu menu_vt">
                                    <li class="menu-item"><a class="menu-link" href="#step1">Шаг 1. Параметры пользователя</a>
                                    </li>
                                    <li class="menu-link"><a class="menu-link" href="#step2">Шаг 2. Способ доставки</a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="#step3">Шаг 3. Способ оплаты</a>
                                    </li>
                                    <li class="menu-item"><a class="menu-item_ACTIVE menu-item" href="#step4">Шаг 4. Подтверждение заказа</a>
                                    </li>

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="Section-content">
                    <form class="form" action="{% url 'orders:payment' %}" method="post">
                    {% csrf_token %}
                        <div class="Order-block Order-block_OPEN" id="step4">
                              <header class="Section-header Section-header_sm">
                                <h2 class="Section-title">Шаг 4. Подтверждение заказа
                                </h2>
                            </header>
                            <!--+div.Order.-confirmation-->
                            <div class="Order-infoBlock">
                                <div class="Order-personal">
                                    <div class="row">
                                        <div class="row-block">
                                            <div class="Order-info">
                                                <div class="Order-infoType">ФИО:
                                                </div>
                                                <div class="Order-infoContent">{{ order.fio }}
                                                </div>
                                            </div>
                                            <div class="Order-info">
                                                <div class="Order-infoType">Телефон:
                                                </div>
                                                <div class="Order-infoContent">+{{ order.phone }}
                                                </div>
                                            </div>
                                            <div class="Order-info">
                                                <div class="Order-infoType">E-mail:
                                                </div>
                                                <div class="Order-infoContent">{{ order.email }}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row-block">
                                            <div class="Order-info Order-info_delivery">
                                                <div class="Order-infoType">Тип доставки:
                                                </div>
                                                <div class="Order-infoContent">{{ order.delivery }}
                                                </div>
                                            </div>
                                            <div class="Order-info">
                                                <div class="Order-infoType">Город:
                                                </div>
                                                <div class="Order-infoContent">{{ order.city }}
                                                </div>
                                            </div>
                                            <div class="Order-info">
                                                <div class="Order-infoType">Адрес:
                                                </div>
                                                <div class="Order-infoContent">{{ order.address }}
                                                </div>
                                            </div>
                                            <div class="Order-info Order-info_pay">
                                                <div class="Order-infoType">Оплата:
                                                </div>
                                                <div class="Order-infoContent">{{ order.payment_method }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% cart_list pk=request.user.profile.pk as cart %}

                                <div class="Cart Cart_order">
                                    {% for element in cart %}
                                        <div class="Cart-product">
                                            <div class="Cart-block Cart-block_row">
                                                <div class="Cart-block Cart-block_pict"><a class="Cart-pict" href="{% url 'products:product' pk=element.product.pk %}"><img class="Cart-img" src="{{ element.product.product_picture.url }}" alt="card.jpg" /></a>
                                                </div>
                                                <div class="Cart-block Cart-block_info"><a class="Cart-title" href="{% url 'products:product' pk=element.product.pk %}">{{ element.product.title }}</a>
                                                    <div class="Cart-desc">{{ element.product.description }}
                                                    </div>
                                                </div>
                                                <div class="Cart-block Cart-block_price">
                                                    <div class="Cart-price">{{ element.product.price }}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="Cart-block Cart-block_row">
                                                <div class="Cart-block Cart-block_amount">{{ element.quantity }} шт.
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                    {% cart_total_price pk=request.user.profile.pk as total_price %}
                                    <div class="Cart-total">
                                        <div class="Cart-block Cart-block_total">
                                            <strong class="Cart-title">Цена за доставку:
                                            </strong><span class="Cart-price">{{ order.delivery_cost }}</span>
                                        </div>
                                        <div class="Cart-block Cart-block_total">
                                            <strong class="Cart-title">Итого:
                                            </strong><span class="Cart-price">{{ total_price }}</span>
                                        </div>
                                        <div class="Cart-block">
                                            <button class="btn btn_primary btn_lg" type="submit">Оплатить
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

orders/templates/orders/payment.html
{% extends "profile/base.html" %}
{% block content %}
    <div class="Middle Middle_top">
        <div class="Middle-top">
            <div class="wrap">
                <div class="Middle-header">
                    <h1 class="Middle-title">Оплата
                    </h1>
                    <ul class="breadcrumbs Middle-breadcrumbs">
                        <li class="breadcrumbs-item"><a href="../../../profile/templates/profile/index.html">home</a>
                        </li>
                        <li class="breadcrumbs-item breadcrumbs-item_current"><span>Оплата</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="Section">
            <div class="wrap">
                <form class="form Payment" action="{% url 'orders:payment_progress' %}" method="get">
                    {% csrf_token %}
                    <div class="Payment-card">
                        <div class="form-group">
                            <label class="form-label">Номер карты
                            </label>
                            <input class="form-input Payment-bill" id="numero1" name="numero1" type="text" placeholder="9999 9999" data-mask="9999 9999" data-validate="require pay" />
                        </div>
                    </div>
                    <div class="Payment-pay"><button type="submit" class="btn btn_primary">Оплатить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

orders/templates/orders/progressPayment.html
{% extends 'profile/base.html' %}
{% block content %}
    </header>
    <div class="Middle Middle_top">
        <div class="Middle-top">
            <div class="wrap">
                <div class="Middle-header">
                    <h1 class="Middle-title">Ожидание оплаты
                    </h1>
                    <ul class="breadcrumbs Middle-breadcrumbs">
                        <li class="breadcrumbs-item"><a href={% url 'index' %}>home</a>
                        </li>
                        <li class="breadcrumbs-item breadcrumbs-item_current"><span>Ожидание оплаты</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="Section">
            <div class="wrap">
                <div class="ProgressPayment">
                    <div class="ProgressPayment-title">Ждем подтверждения оплаты платежной системой
                    </div>
                        <div class="ProgressPayment-icon">
                            <div class="cssload-thecube">
                                <div class="cssload-cube cssload-c1"></div>
                                <div class="cssload-cube cssload-c2"></div>
                                <div class="cssload-cube cssload-c4"></div>
                                <div class="cssload-cube cssload-c3"></div>
                            </div>
                        </div>
                    <script>
                        setTimeout("window,location.href='{% url 'orders:control' num=num %}'",5000)
                    </script>
                </div>
            </div>
        </div>
    </div>
{% endblock %}