cart/urls.py
from django.urls import path
from .views import (
    cart_detail,
    # add_to_cart,
    delete_product,
    update_product,
)

app_name = "cart"

urlpatterns = [
    path("", cart_detail, name="cart_detail"),
    path("delete/<int:id>", delete_product, name="delete_product"),
    path("update/<int:id>", update_product, name="update_product"),
]

online_store/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from profile.views import Profile
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls")),
    path("", include("profile.urls")),
    path("products/", include("products.urls")),
    path("orders/", include("orders.urls")),
    # path('password/', auth_views.PasswordChangeView.as_view(), name='password'),
    # path('password-reset/', auth_views.PasswordResetView.as_view(
    #     template_name='profile/password_reset_form.html'),
    #      name='password_reset'),
    # path('password-reset/done/',
    #      auth_views.PasswordResetCompleteView.as_view(template_name='profile/password_reset_done.html'),
    #      name='password_reset_done'),
    # path('reset/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(template_name='profile/password_reset_confirm.html'),
    #      name='password_reset_confirm'),
    # path('reset/done/',
    #      auth_views.PasswordResetCompleteView.as_view(template_name='profile/password_reset_complete.html'),
    #      name='password_reset_complete'),
    # path('password-change/',
    #      auth_views.PasswordChangeView.as_view(template_name='profile/password_change_form.html'),
    #      name='password_change'),
    # path('password-change/done/',
    #      auth_views.PasswordChangeDoneView.as_view(template_name='profile/password_change_done.html'),
    #      name='password_change_done'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from products.views import (
    CatalogView,
    CategoryView,
    TagView,
    product_detail,
    product_reviews,
    catalog_product,
    all_catalog,
)
from django.conf import settings
from django.conf.urls.static import static

app_name = "products"

urlpatterns = [
    path("catalog/<int:sort>", all_catalog, name="catalog"),
    path("product/<int:pk>/", product_detail, name="product"),
    path("category/<int:pk>/", CategoryView.as_view(), name="category"),
    path("tag/<int:pk>/", TagView.as_view(), name="tag"),
    path("product_reviews/<int:pk>/", product_reviews, name="product_reviews"),
    path("catalog_query/", catalog_product, name="catalog_query"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

profile/urls.py
from django.contrib import admin
from django.urls import include, path
from profile.views import (
    CategoryView,
    register_view,
    AuthorLogoutView,
    Login,
    AccountView,
    ProfileView,
    CartView,
    avatar,
)
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.contrib.auth import views as auth_views

# app_name = 'profile'

urlpatterns = [
    path("", CategoryView.as_view(), name="index"),
    path("register/", register_view, name="register"),
    path("logout/", AuthorLogoutView.as_view(), name="logout"),
    path("login/", Login.as_view(template_name="profile/login.html"), name="login"),
    path("email/", views.PasswordResetView.as_view(), name="email"),
    path("account/", AccountView.as_view(), name="account"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("cart/<int:pk>", CartView.as_view(), name="cart"),
    path("avatar/<int:id>", avatar, name="avatar"),
    path("password/", auth_views.PasswordChangeView.as_view(), name="password"),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="profile/password_reset_form.html"
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="profile/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="profile/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="profile/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "password-change/",
        auth_views.PasswordChangeView.as_view(
            template_name="profile/password_change_form.html"
        ),
        name="password_change",
    ),
    path(
        "password-change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="profile/password_change_done.html"
        ),
        name="password_change_done",
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    def validate_image(fieldfile_obj):
        file_size = fieldfile_obj.file.size
        megabyte_limit = 150.0
        if file_size > megabyte_limit * 1024 * 1024:
            raise Exception(
                "Максимальный размер файла {}MB".format(str(megabyte_limit))
            )

    user = models.OneToOneField(
        User, unique=True, on_delete=models.CASCADE, related_name="profile"
    )
    username = models.CharField(
        default="-------", max_length=50, verbose_name="username", blank=True, null=True
    )
    full_name = models.CharField(
        default="не указано", max_length=50, verbose_name="ФИО пользователя", blank=True
    )
    phone = models.CharField(
        default="Не указано",
        max_length=30,
        verbose_name="номер телефона",
        blank=True,
        null=True,
        unique=True,
    )
    email = models.EmailField(
        verbose_name="email пользователя", blank=True, unique=True
    )
    avatar = models.ImageField(
        upload_to="catalog/files/", null=True, validators=[validate_image], default=""
    )

    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили пользователей"

    def __str__(self):
        return self.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created and instance.is_superuser:
        Profile.objects.create(user=instance)

profile/forms.py
from django import forms
from profile.models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class AuthorRegisterForm(forms.Form):
    full_name = forms.CharField(required=True, help_text="имя пользователя")
    phone = forms.CharField(required=True, help_text="номер телефона")
    email = forms.EmailField(required=True, help_text="email")
    login = forms.CharField(required=True, help_text="логин")
    password = forms.CharField(required=True, help_text="пароль")

profile/views.py
from django.contrib import messages
from django.http import HttpRequest
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView

from profile.models import Profile
from products.models import (
    Product,
    TagsFile,
    Reviews,
    Specifications,
    Shop,
    Sales,
    CategoryProduct,
)
from orders.models import Order, OrderHistory
from cart.models import Cart, Payment

from profile.forms import AuthorRegisterForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LogoutView, LoginView
from django.contrib.auth.models import User
import os
from django.core.exceptions import ValidationError
from cart.forms import CartAddProductForm


def register_view(request):
    """Функция регистрации нового пользователя"""

    if request.method == "POST":
        form = AuthorRegisterForm(request.POST)
        if form.is_valid():
            full_name = form.cleaned_data.get("full_name")
            phone = form.cleaned_data.get("phone")
            email = form.cleaned_data.get("email")
            raw_password = form.cleaned_data.get("password")
            username = form.cleaned_data.get("login")
            user = User.objects.create_user(
                username=username, first_name=full_name, email=email
            )
            user.set_password(raw_password)
            user.save()
            login(request, user)
            Profile.objects.create(
                user=user,
                username=username,
                full_name=full_name,
                phone=phone,
                email=email,
            )
        return redirect("/")

    return render(request, "profile/registr.html")


class AuthorLogoutView(LogoutView):
    """Выход из учетной записи"""

    next_page = "/"


class Login(LoginView):
    """Вход в учетную запись"""

    def form_valid(self, form):
        return super().form_valid(form)


class CategoryView(View):
    """Формирование списка категорий, популярных товаров,
    лимитированных, баннеров и путей до изображений этих категорий"""

    def get(self, request):
        date = CategoryProduct.objects.all()
        file_name_list = []
        for image in date:
            file = os.path.basename(str(image.image))
            file_name_list.append(file)
        category = zip(date, file_name_list)
        popular_product = Product.objects.all().order_by("-reviews")[:8]
        limited_edition = Product.objects.filter(free_delivery=False)
        banners = Product.objects.all().order_by("-rating")
        return render(
            request,
            "profile/index.html",
            {
                "popular_product": popular_product,
                "limited_edition": limited_edition,
                "banners": banners,
            },
        )


class AccountView(View):
    def get(self, request: HttpRequest):
        return render(request, "profile/account.html")


class ProfileView(View):
    def get(self, request: HttpRequest):
        return render(request, "profile/profile.html")


class CartView(View):
    def get(self, request: HttpRequest, **kwargs):
        cart = Cart.objects.filter(username=kwargs["pk"])
        total_price = 0
        for product in cart:
            total_price += product.product.price * product.quantity
        return render(request, "cart/cart.html", {"total_price": total_price})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(
        request,
        "products/product.html",
        {"product": product, "cart_product_form": cart_product_form},
    )


def avatar(request: HttpRequest, **kwargs):
    user = Profile.objects.get(user=kwargs["id"])
    user_avatar = request.POST.get("avatar")

    Profile.objects.filter(user=kwargs["id"]).update(
        avatar=user_avatar,
    )
    return redirect(request.META["HTTP_REFERER"])

profile/templates/include/catalog_head.html
   {% load products_tags %}
    <div class="Middle Middle_top">
        <div class="Section Section_column Section_columnLeft">
            <div class="wrap">
                <div class="Section-column">
                    <div class="Section-columnSection">
                        <header class="Section-header">
                            <strong class="Section-title">Фильтр
                            </strong>
                        </header>
                        <div class="Section-columnContent">
                            <form class="form" action="#" method="post">
                                <div class="form-group">
                                    <div class="range Section-columnRange">
                                        <input class="range-line" id="price" name="price" type="text" data-type="double" data-min="7" data-max="50" data-from="7" data-to="27" />
                                        <div class="range-price">Цена:&#32;
                                            <div class="rangePrice">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input class="form-input form-input_full" id="title" name="title" type="text" placeholder="Название" />
                                </div>
                                <div class="form-group">
                                    <!-- - var options = setOptions(items, ['value', 'selected', 'disabled']);-->
                                </div>
                                <div class="form-group">
                                    <label class="toggle">
                                        <input type="checkbox" /><span class="toggle-box"></span><span class="toggle-text">Только товары в наличии</span>
                                    </label>
                                </div>
                                <div class="form-group">
                                    <label class="toggle">
                                        <input type="checkbox" /><span class="toggle-box"></span><span class="toggle-text">С бесплатной доставкой</span>
                                    </label>
                                </div>
                                <div class="form-group">
                                    <div class="buttons"><a class="btn btn_square btn_dark btn_narrow" href="#">Фильтр</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="Section-columnSection">
                        <header class="Section-header">
                            <strong class="Section-title">Популярные тэги
                            </strong>
                        </header>
                        {% all_tags as tags %}
                        <div class="ProductCard-tags">
                            {% for tag in tags %}
                                <a href="{% url 'products:tag' pk=tag.pk %}">{{ tag }}</a>
                            {% endfor %}

                        </div>
                    </div>
                </div>
                <div class="Section-content">
                    <div class="Sort">
                        <div class="Sort-title">Сортировать по:
                        </div>
                        <div class="Sort-variants"><a class="Sort-sortBy Sort-sortBy_dec" href="{% url 'products:catalog' sort=1 %}">Популярности</a><a class="Sort-sortBy Sort-sortBy_dec" href="{% url 'products:catalog' sort=2 %}">Цене</a><a class="Sort-sortBy" href="{% url 'products:catalog' sort=3 %}">Отзывам</a><a class="Sort-sortBy Sort-sortBy_inc" href="{% url 'products:catalog' sort=4 %}">Новизне</a>
                        </div>
                    </div>
                    <div class="Cards">

profile/templates/include/head.html
{% load static %}
<head>
    <title>Megano</title>
    <meta name="description" content="Описание страницы">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    <link href="favicon.ico" rel="static 'shortcut icon">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Regular.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold_Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light_Italic.woff' %}" as="font">
    <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/basic.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/extra.css' %}">
    <script src="{% static 'assets/plg/CountDown/countdown.js' %}"></script>
    <!--[if lt IE 9]>
    <script src="{% static 'http://html5shiv.googlecode.com/svn/trunk/html5.js' %}"></script><![endif]-->
</head>